name: derredor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  email_validator: ^3.0.0
  mysql1: ^0.20.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/initial_page/
    - assets/images/backgrounds/login_page/
    - assets/icons/


